# Generated by Django 6.0.2 on 2026-03-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiztype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Title (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='quiz.difficulty', verbose_name='Difficulty')),
                ('quiz_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='quiz.quiztype', verbose_name='Quiz type')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='quiz.section', verbose_name='Section')),
                ('tags', models.ManyToManyField(blank=True, related_name='quizzes', to='quiz.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quiz"."quiz',
            },
        ),
        migrations.CreateModel(
            name='CodeCompletionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Code')),
                ('blanks', models.CharField(max_length=100, verbose_name='Blanks')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Answer')),
                ('hint_ru', models.TextField(blank=True, null=True, verbose_name='Hint (RU)')),
                ('hint_en', models.TextField(blank=True, null=True, verbose_name='Hint (EN)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_completion_questions', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question Code Completion',
                'verbose_name_plural': 'Questions Code Completion',
                'db_table': 'quiz"."code_completion_question',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsyncSorterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Code')),
                ('blocks', models.JSONField(default=list, verbose_name='Blocks')),
                ('correct_sequence', models.JSONField(default=list, verbose_name='Answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='async_sorter_questions', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question Async Sorter',
                'verbose_name_plural': 'Questions Async Sorter',
                'db_table': 'quiz"."async_sorter_question',
                'ordering': ['id'],
            },
        ),
    ]
