# Generated by Django 6.0.2 on 2026-03-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_codecompletionquestion_asyncsorterquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description_en',
            field=models.TextField(default='...', verbose_name='Description (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_ru',
            field=models.TextField(default='...', verbose_name='Description (RU)'),
            preserve_default=False,
        ),
    ]
