# Generated by Django 6.0.2 on 2026-03-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_description_en_quiz_description_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time limit'),
        ),
    ]
