# Generated by Django 6.0.2 on 2026-03-19 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Title (RU)')),
                ('text_en', models.TextField(verbose_name='Title (EN)')),
                ('option_a_ru', models.CharField(max_length=255, verbose_name='Option A (RU)')),
                ('option_a_en', models.CharField(max_length=255, verbose_name='Option A (EN)')),
                ('option_b_ru', models.CharField(max_length=255, verbose_name='Option B (RU)')),
                ('option_b_en', models.CharField(max_length=255, verbose_name='Option B (EN)')),
                ('option_c_ru', models.CharField(max_length=255, verbose_name='Option C (RU)')),
                ('option_c_en', models.CharField(max_length=255, verbose_name='Option C (EN)')),
                ('option_d_ru', models.CharField(max_length=255, verbose_name='Option D (RU)')),
                ('option_d_en', models.CharField(max_length=255, verbose_name='Option D (EN)')),
                ('correct_answer', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, verbose_name='Correct answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice_questions', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question Single Choice',
                'verbose_name_plural': 'Questions Single Choice',
                'db_table': 'quiz"."single_choice_question',
                'ordering': ['id'],
            },
        ),
    ]
