# Generated by Django 6.0.2 on 2026-03-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_singlechoicequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_ru', models.TextField(verbose_name='Statement (RU)')),
                ('statement_en', models.TextField(verbose_name='Statement (EN)')),
                ('correct_answer', models.BooleanField(verbose_name='Correct answer')),
                ('explanation_ru', models.TextField(blank=True, null=True, verbose_name='Explanation (RU)')),
                ('explanation_en', models.TextField(blank=True, null=True, verbose_name='Explanation (EN)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_questions', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question True/False',
                'verbose_name_plural': 'Questions True/False',
                'db_table': 'quiz"."true_false_question',
                'ordering': ['id'],
            },
        ),
    ]
