# Generated by Django 6.0.2 on 2026-03-26 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quizresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adding date')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='quiz.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite quiz',
                'verbose_name_plural': 'Favorites quizzes',
                'db_table': 'quiz"."favorite_quiz',
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
