# Generated by Django 6.0.2 on 2026-03-28 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_favoritequiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOrderingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Task (RU)')),
                ('text_en', models.TextField(verbose_name='Task (EN)')),
                ('code_lines', models.JSONField(verbose_name='Code lines')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_ordering_questions', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question Code ordering',
                'verbose_name_plural': 'Questions Code ordering',
                'db_table': 'quiz"."code_ordering_question',
                'ordering': ['id'],
            },
        ),
    ]
